#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpKind {
    End = 1000,
    Literal,
    Signature,
    Copy,
    Checksum,
    Reserved,
}

#[derive(Debug)]
pub struct Command {
    pub kind: OpKind,
    pub immediate: u8,
    pub len1: u8,
    pub len2: u8,
}

#[repr(u8)]
#[derive(Debug, Clone, Copy)]
pub enum Op {
    EndOp,
    Literal1,
    Literal2,
    Literal3,
    Literal4,
    Literal5,
    Literal6,
    Literal7,
    Literal8,
    Literal9,
    Literal10,
    Literal11,
    Literal12,
    Literal13,
    Literal14,
    Literal15,
    Literal16,
    Literal17,
    Literal18,
    Literal19,
    Literal20,
    Literal21,
    Literal22,
    Literal23,
    Literal24,
    Literal25,
    Literal26,
    Literal27,
    Literal28,
    Literal29,
    Literal30,
    Literal31,
    Literal32,
    Literal33,
    Literal34,
    Literal35,
    Literal36,
    Literal37,
    Literal38,
    Literal39,
    Literal40,
    Literal41,
    Literal42,
    Literal43,
    Literal44,
    Literal45,
    Literal46,
    Literal47,
    Literal48,
    Literal49,
    Literal50,
    Literal51,
    Literal52,
    Literal53,
    Literal54,
    Literal55,
    Literal56,
    Literal57,
    Literal58,
    Literal59,
    Literal60,
    Literal61,
    Literal62,
    Literal63,
    Literal64,
    LiteralN1,
    LiteralN2,
    LiteralN4,
    LiteralN8,
    CopyN1N1,
    CopyN1N2,
    CopyN1N4,
    CopyN1N8,
    CopyN2N1,
    CopyN2N2,
    CopyN2N4,
    CopyN2N8,
    CopyN4N1,
    CopyN4N2,
    CopyN4N4,
    CopyN4N8,
    CopyN8N1,
    CopyN8N2,
    CopyN8N4,
    CopyN8N8,
    Reserved85,
    Reserved86,
    Reserved87,
    Reserved88,
    Reserved89,
    Reserved90,
    Reserved91,
    Reserved92,
    Reserved93,
    Reserved94,
    Reserved95,
    Reserved96,
    Reserved97,
    Reserved98,
    Reserved99,
    Reserved100,
    Reserved101,
    Reserved102,
    Reserved103,
    Reserved104,
    Reserved105,
    Reserved106,
    Reserved107,
    Reserved108,
    Reserved109,
    Reserved110,
    Reserved111,
    Reserved112,
    Reserved113,
    Reserved114,
    Reserved115,
    Reserved116,
    Reserved117,
    Reserved118,
    Reserved119,
    Reserved120,
    Reserved121,
    Reserved122,
    Reserved123,
    Reserved124,
    Reserved125,
    Reserved126,
    Reserved127,
    Reserved128,
    Reserved129,
    Reserved130,
    Reserved131,
    Reserved132,
    Reserved133,
    Reserved134,
    Reserved135,
    Reserved136,
    Reserved137,
    Reserved138,
    Reserved139,
    Reserved140,
    Reserved141,
    Reserved142,
    Reserved143,
    Reserved144,
    Reserved145,
    Reserved146,
    Reserved147,
    Reserved148,
    Reserved149,
    Reserved150,
    Reserved151,
    Reserved152,
    Reserved153,
    Reserved154,
    Reserved155,
    Reserved156,
    Reserved157,
    Reserved158,
    Reserved159,
    Reserved160,
    Reserved161,
    Reserved162,
    Reserved163,
    Reserved164,
    Reserved165,
    Reserved166,
    Reserved167,
    Reserved168,
    Reserved169,
    Reserved170,
    Reserved171,
    Reserved172,
    Reserved173,
    Reserved174,
    Reserved175,
    Reserved176,
    Reserved177,
    Reserved178,
    Reserved179,
    Reserved180,
    Reserved181,
    Reserved182,
    Reserved183,
    Reserved184,
    Reserved185,
    Reserved186,
    Reserved187,
    Reserved188,
    Reserved189,
    Reserved190,
    Reserved191,
    Reserved192,
    Reserved193,
    Reserved194,
    Reserved195,
    Reserved196,
    Reserved197,
    Reserved198,
    Reserved199,
    Reserved200,
    Reserved201,
    Reserved202,
    Reserved203,
    Reserved204,
    Reserved205,
    Reserved206,
    Reserved207,
    Reserved208,
    Reserved209,
    Reserved210,
    Reserved211,
    Reserved212,
    Reserved213,
    Reserved214,
    Reserved215,
    Reserved216,
    Reserved217,
    Reserved218,
    Reserved219,
    Reserved220,
    Reserved221,
    Reserved222,
    Reserved223,
    Reserved224,
    Reserved225,
    Reserved226,
    Reserved227,
    Reserved228,
    Reserved229,
    Reserved230,
    Reserved231,
    Reserved232,
    Reserved233,
    Reserved234,
    Reserved235,
    Reserved236,
    Reserved237,
    Reserved238,
    Reserved239,
    Reserved240,
    Reserved241,
    Reserved242,
    Reserved243,
    Reserved244,
    Reserved245,
    Reserved246,
    Reserved247,
    Reserved248,
    Reserved249,
    Reserved250,
    Reserved251,
    Reserved252,
    Reserved253,
    Reserved254,
    Reserved255,
}

pub static OP2CMD: &[Command] = &[
    Command {
        kind: OpKind::End,
        immediate: 0,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 1,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 2,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 3,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 4,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 5,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 6,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 7,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 8,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 9,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 10,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 11,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 12,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 13,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 14,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 15,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 16,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 17,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 18,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 19,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 20,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 21,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 22,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 23,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 24,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 25,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 26,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 27,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 28,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 29,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 30,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 31,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 32,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 33,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 34,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 35,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 36,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 37,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 38,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 39,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 40,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 41,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 42,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 43,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 44,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 45,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 46,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 47,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 48,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 49,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 50,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 51,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 52,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 53,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 54,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 55,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 56,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 57,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 58,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 59,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 60,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 61,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 62,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 63,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 64,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 0,
        len1: 1,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 0,
        len1: 2,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 0,
        len1: 4,
        len2: 0,
    },
    Command {
        kind: OpKind::Literal,
        immediate: 0,
        len1: 8,
        len2: 0,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 1,
        len2: 1,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 1,
        len2: 2,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 1,
        len2: 4,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 1,
        len2: 8,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 2,
        len2: 1,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 2,
        len2: 2,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 2,
        len2: 4,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 2,
        len2: 8,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 4,
        len2: 1,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 4,
        len2: 2,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 4,
        len2: 4,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 4,
        len2: 8,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 8,
        len2: 1,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 8,
        len2: 2,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 8,
        len2: 4,
    },
    Command {
        kind: OpKind::Copy,
        immediate: 0,
        len1: 8,
        len2: 8,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 85,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 86,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 87,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 88,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 89,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 90,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 91,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 92,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 93,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 94,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 95,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 96,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 97,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 98,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 99,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 100,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 101,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 102,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 103,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 104,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 105,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 106,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 107,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 108,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 109,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 110,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 111,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 112,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 113,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 114,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 115,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 116,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 117,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 118,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 119,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 120,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 121,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 122,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 123,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 124,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 125,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 126,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 127,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 128,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 129,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 130,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 131,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 132,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 133,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 134,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 135,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 136,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 137,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 138,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 139,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 140,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 141,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 142,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 143,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 144,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 145,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 146,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 147,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 148,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 149,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 150,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 151,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 152,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 153,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 154,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 155,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 156,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 157,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 158,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 159,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 160,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 161,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 162,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 163,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 164,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 165,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 166,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 167,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 168,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 169,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 170,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 171,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 172,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 173,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 174,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 175,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 176,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 177,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 178,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 179,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 180,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 181,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 182,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 183,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 184,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 185,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 186,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 187,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 188,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 189,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 190,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 191,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 192,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 193,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 194,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 195,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 196,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 197,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 198,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 199,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 200,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 201,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 202,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 203,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 204,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 205,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 206,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 207,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 208,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 209,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 210,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 211,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 212,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 213,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 214,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 215,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 216,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 217,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 218,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 219,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 220,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 221,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 222,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 223,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 224,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 225,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 226,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 227,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 228,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 229,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 230,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 231,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 232,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 233,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 234,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 235,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 236,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 237,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 238,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 239,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 240,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 241,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 242,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 243,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 244,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 245,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 246,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 247,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 248,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 249,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 250,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 251,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 252,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 253,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 254,
        len1: 0,
        len2: 0,
    },
    Command {
        kind: OpKind::Reserved,
        immediate: 255,
        len1: 0,
        len2: 0,
    },
];
